# See http://about.travis-ci.org/docs/user/build-configuration/
language: java
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - damian.mcdonald1979@gmail.com
jdk:
  - oraclejdk8